<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Click to see screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Wed_May_29_02_29_18_EDT_2019.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Wed_May_29_02_29_18_EDT_2019.jpg><img src=Wed_May_29_02_29_18_EDT_2019.jpg height=200 width=200</img></a>]]>
    </line>
  </reporter-output>
  <suite name="Page Object Model with Page Factories" duration-ms="460789" started-at="2019-05-29T06:21:38Z" finished-at="2019-05-29T06:29:19Z">
    <groups>
    </groups>
    <test name="Sign in Test" duration-ms="14119" started-at="2019-05-29T06:21:38Z" finished-at="2019-05-29T06:21:53Z">
      <class name="com.frankbahar.testcases.SignInTest">
        <test-method status="SKIP" signature="signInTest(java.util.Hashtable)[pri:0, instance:com.frankbahar.testcases.SignInTest@1f2586d6]" name="signInTest" duration-ms="8" started-at="2019-05-29T02:21:38Z" data-provider="dp" finished-at="2019-05-29T02:21:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Selenium@123, runmode=N, username=frankbahar07@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test as the Run Mode is NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test as the Run Mode is NO
	at com.frankbahar.testcases.SignInTest.signInTest(SignInTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.frankbahar.testcases.SignInTest@1f2586d6]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-05-29T02:21:39Z" finished-at="2019-05-29T02:21:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="signInTest(java.util.Hashtable)[pri:0, instance:com.frankbahar.testcases.SignInTest@1f2586d6]" name="signInTest" duration-ms="12892" started-at="2019-05-29T02:21:39Z" data-provider="dp" finished-at="2019-05-29T02:21:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=1231313.0, runmode=Y, username=java@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.frankbahar.testcases.SignInTest@1f2586d6]" name="tearDown" is-config="true" duration-ms="914" started-at="2019-05-29T02:21:52Z" finished-at="2019-05-29T02:21:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.frankbahar.testcases.SignInTest -->
    </test> <!-- Sign in Test -->
    <test name="Flight Search Test" duration-ms="434524" started-at="2019-05-29T06:22:05Z" finished-at="2019-05-29T06:29:19Z">
      <class name="com.frankbahar.testcases.FlightSearchTest">
        <test-method status="FAIL" signature="flightSearchTest(java.util.Hashtable)[pri:0, instance:com.frankbahar.testcases.FlightSearchTest@7eac9008]" name="flightSearchTest" duration-ms="432106" started-at="2019-05-29T02:22:05Z" data-provider="dp" finished-at="2019-05-29T02:29:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{returning=6/15/19, departing=6/10/19, runmode=Y, noOfChildren=0.0, noOfAdults=2.0, to=Cancun, Quintana Roo, Mexico (CUN), from=New York, United States of America (NYC)}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [8] but found [7]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [8] but found [7]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.frankbahar.errorcollectors.ErrorCollector.assertEquals(ErrorCollector.java:38)
	at com.frankbahar.errorcollectors.ErrorCollector.verifyEquals(ErrorCollector.java:102)
	at com.frankbahar.testcases.FlightSearchTest.flightSearchTest(FlightSearchTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Wed_May_29_02_29_18_EDT_2019.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Wed_May_29_02_29_18_EDT_2019.jpg><img src=Wed_May_29_02_29_18_EDT_2019.jpg height=200 width=200</img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- flightSearchTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.frankbahar.testcases.FlightSearchTest@7eac9008]" name="tearDown" is-config="true" duration-ms="1514" started-at="2019-05-29T02:29:18Z" finished-at="2019-05-29T02:29:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.frankbahar.testcases.FlightSearchTest -->
    </test> <!-- Flight Search Test -->
  </suite> <!-- Page Object Model with Page Factories -->
</testng-results>
